title: Joana Trashlieva
logo: assets/headshot.jpg
email: j.trashlieva@gmail.com
description:  Software Developer <p> & </p> <p> Point Guard </p> <div class='social'>ğŸ“ Reading, UK </div> <div class='social'> âœ‰ï¸ j.trashlieva@gmail.com </div>  <br /> <div class='social-icons'>
    <a href='https://github.com/JoanaTrashlieva' target='_blank'><img src='/assets/icons/github.png' alt='GitHub Logo' /></a>
    <a href='https://www.linkedin.com/in/joana-trashlieva/' target='_blank'><img src='/assets/icons/linkedin.png' alt='LinkedIn Logo' /></a>
    <a href='https://twitter.com/trashlieva' target='_blank'><img src='/assets/icons/twitter.png' alt='Twitter Logo' /></a></div>
google_analytics: UA-186565906-1
show_downloads: false
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.joanatrashlieva.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed